### ISSUE TITLE
Error on Alfresco 4.2.a

### ISSUE THREAD

**Issue by softwareloop** [softwareloop/uploader-plus#60]
```
2014-11-19 16:03:29,707  ERROR [freemarker.runtime] [http-bio-8080-exec-11] Template processing error: "Expression fileUploadSizeLimit is undefined on line 18, column 42 in org/alfresco/components/upload/html-upload.get.html.ftl."
 
Expression fileUploadSizeLimit is undefined on line 18, column 42 in org/alfresco/components/upload/html-upload.get.html.ftl.
The problematic instruction:
----------
==> ${fileUploadSizeLimit} [on line 18, column 40 in org/alfresco/components/upload/html-upload.get.html.ftl]
 in user-directive inlineScript [on line 17, column 5 in org/alfresco/components/upload/html-upload.get.html.ftl]
 in user-directive markup [on line 15, column 1 in org/alfresco/components/upload/html-upload.get.html.ftl]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression fileUploadSizeLimit is undefined on line 18, column 42 in org/alfresco/components/upload/html-upload.get.html.ftl.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
	at freemarker.core.Expression.getStringValue(Expression.java:118)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment$3.render(Environment.java:246)
	at org.springframework.extensions.directives.AddInlineJavaScriptDirective.createExtensibilityDirectiveData(AddInlineJavaScriptDirective.java:67)
	at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.execute(AbstractExtensibilityDirective.java:133)
	at org.springframework.extensions.directives.JavaScriptDependencyDirective.execute(JavaScriptDependencyDirective.java:79)
	at freemarker.core.Environment.visit(Environment.java:274)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:126)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment$3.render(Environment.java:246)
	at org.springframework.extensions.surf.extensibility.impl.DefaultExtensibilityDirectiveData.render(DefaultExtensibilityDirectiveData.java:119)
	at org.springframework.extensions.surf.extensibility.impl.ExtensibilityModelImpl.merge(ExtensibilityModelImpl.java:408)
	at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.merge(AbstractExtensibilityDirective.java:169)
	at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.execute(AbstractExtensibilityDirective.java:137)
	at freemarker.core.Environment.visit(Environment.java:274)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:126)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:171)
	at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:858)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
	at org.springframework.extensions.webscripts.PresentationContainer.executeScript(PresentationContainer.java:70)
	at org.springframework.extensions.webscripts.LocalWebScriptRuntimeContainer.executeScript(LocalWebScriptRuntimeContainer.java:240)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:377)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
	at org.springframework.extensions.webscripts.WebScriptProcessor.executeBody(WebScriptProcessor.java:310)
	at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:57)
	at org.springframework.extensions.surf.render.RenderService.process(RenderService.java:599)
	at org.springframework.extensions.surf.render.RenderService.renderSubComponent(RenderService.java:505)
	at org.springframework.extensions.surf.render.RenderService.renderChromeInclude(RenderService.java:1284)
	at org.springframework.extensions.directives.ChromeIncludeFreeMarkerDirective.execute(ChromeIncludeFreeMarkerDirective.java:81)
	at freemarker.core.Environment.visit(Environment.java:274)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:126)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IfBlock.accept(IfBlock.java:82)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:171)
	at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:438)
	at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:57)
	at org.springframework.extensions.surf.render.RenderService.processRenderable(RenderService.java:204)
	at org.springframework.extensions.surf.render.bean.ChromeRenderer.body(ChromeRenderer.java:95)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.bean.ChromeRenderer.render(ChromeRenderer.java:86)
	at org.springframework.extensions.surf.render.RenderService.processComponent(RenderService.java:432)
	at org.springframework.extensions.surf.render.bean.ComponentRenderer.body(ComponentRenderer.java:94)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.RenderService.renderComponent(RenderService.java:961)
	at org.springframework.extensions.surf.render.RenderService.renderRegionComponents(RenderService.java:900)
	at org.springframework.extensions.surf.render.RenderService.renderChromeInclude(RenderService.java:1263)
	at org.springframework.extensions.directives.ChromeIncludeFreeMarkerDirective.execute(ChromeIncludeFreeMarkerDirective.java:81)
	at freemarker.core.Environment.visit(Environment.java:274)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:126)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:171)
	at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:438)
	at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:57)
	at org.springframework.extensions.surf.render.RenderService.processRenderable(RenderService.java:204)
	at org.springframework.extensions.surf.render.bean.ChromeRenderer.body(ChromeRenderer.java:95)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.bean.ChromeRenderer.render(ChromeRenderer.java:86)
	at org.springframework.extensions.surf.render.bean.RegionRenderer.body(RegionRenderer.java:99)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.RenderService.renderRegion(RenderService.java:851)
	at org.springframework.extensions.directives.RegionDirectiveData.render(RegionDirectiveData.java:91)
	at org.springframework.extensions.surf.extensibility.impl.ExtensibilityModelImpl.merge(ExtensibilityModelImpl.java:408)
	at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.merge(AbstractExtensibilityDirective.java:169)
	at org.springframework.extensions.surf.extensibility.impl.AbstractExtensibilityDirective.execute(AbstractExtensibilityDirective.java:137)
	at freemarker.core.Environment.visit(Environment.java:274)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:126)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.visit(Environment.java:406)
	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:93)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Macro$Context.runMacro(Macro.java:172)
	at freemarker.core.Environment.visit(Environment.java:614)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at org.springframework.extensions.webscripts.processor.FTLTemplateProcessor.process(FTLTemplateProcessor.java:171)
	at org.springframework.extensions.webscripts.WebTemplateProcessor.executeBody(WebTemplateProcessor.java:438)
	at org.springframework.extensions.surf.render.AbstractProcessor.execute(AbstractProcessor.java:57)
	at org.springframework.extensions.surf.render.RenderService.processTemplate(RenderService.java:721)
	at org.springframework.extensions.surf.render.bean.TemplateInstanceRenderer.body(TemplateInstanceRenderer.java:140)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.bean.PageRenderer.body(PageRenderer.java:85)
	at org.springframework.extensions.surf.render.AbstractRenderer.render(AbstractRenderer.java:77)
	at org.springframework.extensions.surf.render.RenderService.renderPage(RenderService.java:762)
	at org.springframework.extensions.surf.mvc.PageView.dispatchPage(PageView.java:419)
	at org.springframework.extensions.surf.mvc.PageView.renderView(PageView.java:314)
	at org.springframework.extensions.surf.mvc.AbstractWebFrameworkView.renderMergedOutputModel(AbstractWebFrameworkView.java:316)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:250)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1047)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:817)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:355)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by softwareloop** [comment]
Older versions of Alfresco 4.2.x are not supported
